/* ----------------------------------------------------------------------- */
/* Template source file generated by piklab */
#include <pic16f690.h>

/* ----------------------------------------------------------------------- */
/* Configuration bits: adapt to your setup and needs */
typedef unsigned int word;
word __at 0x2007 CONFIG = _EXTRC_OSC_CLKOUT & _WDT_ON & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOR_ON & _IESO_ON & _FCMEN_ON;

void isr() __interrupt 0 {                                                                                                            /* megszakítás beállító rutin */
    /* << megszakítási kód helye >> */
}

void main() {
    /* << ide a kódot >> */
}
